board: Board.hpp Board.cpp testBoard.cpp
	g++ -Wall Board.cpp testBoard.cpp -o testBoard.out
	./testBoard.out

reader: Board.hpp Board.cpp T3Reader.hpp T3Reader.cpp testReader.cpp textInput.txt
	g++ -Wall Board.cpp T3Reader.cpp testReader.cpp -o testReader.out
	./testReader.out