box: Box.cpp boxMain.cpp Box.hpp
	g++ -Wall -o box.out Box.cpp boxMain.cpp

taxi: Taxicab.cpp Taxicab.hpp taxicabMain.cpp
	g++ -Wall -o taxi.out Taxicab.cpp taxicabMain.cpp

clean:
	rm box.out
	rm taxi.out